---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: active-defense-scheduler2
  namespace: kube-system
  labels:
    component: active-defense-scheduler2
spec:
  replicas: 1
  selector:
    matchLabels:
      component: active-defense-scheduler2
  template:
    metadata:
      labels:
        component: active-defense-scheduler2
    spec:
      serviceAccount: active-defense-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-config2
      containers:
        - name: active-defense-scheduler
          image: weyg0/active-defense-scheduler:v0.1.1
          imagePullPolicy: IfNotPresent
          args:
            - active-defense-scheduler
            - --config=/scheduler/scheduler-config.yaml
            - --v=3
          resources:
            requests:
              cpu: "300m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /scheduler
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: active-defense-cr
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - events
      - namespaces
    verbs:
      - create
      - get
      - update
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - active-defense-scheduler
    resources:
      - endpoints
    verbs:
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - bindings
      - pods/binding
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - csinodes
      - csidrivers
      - csistoragecapacities
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - core.run-linux.com
    resources:
      - scvs
    verbs:
      - delete
      - get
      - list
      - watch
      - update
      - patch
      - create
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config2
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: active-defense-scheduler
    profiles:
      - plugins:
          preEnqueue:
            enabled:
              - name: "active-defense"
            disabled:
              - name: "*"
          queueSort:
            enabled:
              - name: "active-defense"
            disabled:
              - name: "*"
          postBind:
            enabled:
              - name: "active-defense"
            disabled:
              - name: "*"   
        schedulerName: active-defense-scheduler 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: active-defense-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: active-defense-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: active-defense-cr
subjects:
  - kind: ServiceAccount
    name: active-defense-sa
    namespace: kube-system

